services:
  - type: web
    name: members-only-app
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: members-only-db
          property: connectionString

databases:
  - name: members-only-db
    engine: postgresql
    plan: free
    defaultDatabaseName: members_only_db
    user: samy
